// Learn about helper / utils functions
// - we don't want to re-invent the wheel
// - where is the documentation to find all this helper or utils function?

// Function to learn today
// All are ARRAY Family (array helper functions)

// - at - DONE
const array1 = [5, 12, 8, 130, 44];

// -- instead of using array lenght, we can use "at" to get the last element
console.log(array1[array1-length - 1])
console.log(array1.at(-1))

// - Sort - 
// -- ES6
console.log( array1.sort())
console.log( array1.sort((a, b) => a-b) )

// - Find
// - Filter
// - Join
// - Loop
// -- For loop (forEach, map)
// -- While loop
// -- do while
// -- Switch

